version: "3.8"

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
    volumes:
     - "./cockroach-data/crdb:/cockroach/cockroach-data"
     - "./db_init.sh:/db_init.sh"
    entrypoint: "/bin/bash"
    command: /db_init.sh